import {
  AdjustmentsHorizontalIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowUpRightIcon,
  BanknotesIcon,
  Bars3Icon,
  BeakerIcon,
  BellIcon,
  BoltIcon,
  BriefcaseIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ClockIcon,
  CloudIcon,
  CubeTransparentIcon,
  DocumentChartBarIcon,
  DocumentTextIcon,
  ExclamationCircleIcon,
  EyeIcon,
  EyeSlashIcon,
  FlagIcon,
  HomeIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  PhoneIcon,
  ShieldCheckIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  TrophyIcon,
  TruckIcon,
  UserCircleIcon,
  UserGroupIcon,
  UsersIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';

export const heroIcons = {
  admin: ShieldCheckIcon,
  air: BeakerIcon,
  announcement: MegaphoneIcon,
  arrowDownRight: ArrowDownRightIcon,
  arrowLeft: ArrowLeftIcon,
  arrowPath: ArrowPathIcon,
  arrowUpRight: ArrowUpRightIcon,
  banknotes: BanknotesIcon,
  bars: Bars3Icon,
  bell: BellIcon,
  bolt: BoltIcon,
  briefcase: BriefcaseIcon,
  building: BuildingOffice2Icon,
  calendar: CalendarDaysIcon,
  check: CheckCircleIcon,
  chevronDown: ChevronDownIcon,
  city: BuildingLibraryIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  dashboard: ChartBarSquareIcon,
  document: DocumentTextIcon,
  energy: BoltIcon,
  eye: EyeIcon,
  eyeSlash: EyeSlashIcon,
  flag: FlagIcon,
  government: BuildingLibraryIcon,
  health: SparklesIcon,
  home: HomeIcon,
  map: MapIcon,
  mapPin: MapPinIcon,
  metrics: ChartBarIcon,
  park: SunIcon,
  phone: PhoneIcon,
  people: UserGroupIcon,
  profile: UserCircleIcon,
  report: DocumentChartBarIcon,
  road: AdjustmentsHorizontalIcon,
  school: CubeTransparentIcon,
  search: MagnifyingGlassIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  sun: SunIcon,
  trash: TruckIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  users: UsersIcon,
  warning: ExclamationCircleIcon,
  water: BeakerIcon,
  xCircle: XCircleIcon,
  xMark: XMarkIcon,
};

export default function HeroIcon({ name, className = '', ...props }) {
  const Icon = heroIcons[name] || SparklesIcon;
  return <Icon className={`hero-icon ${className}`.trim()} aria-hidden="true" {...props} />;
}
