import {
  ShieldAlert,
  Wind,
  Megaphone,
  ArrowDownRight,
  ArrowLeft,
  RotateCw,
  ArrowUpRight,
  Coins,
  Menu,
  Bell,
  Zap,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Building,
  Clock,
  Cloud,
  LayoutDashboard,
  FileText,
  Eye,
  EyeOff,
  Flag,
  Landmark,
  Activity,
  Home,
  Map,
  MapPin,
  TrendingUp,
  Sun,
  Phone,
  Users,
  User,
  FileSpreadsheet,
  Milestone,
  GraduationCap,
  Search,
  Sparkles,
  Star,
  Sun as SunIcon,
  Trash2,
  Trophy,
  Truck,
  AlertTriangle,
  Droplets,
  XCircle,
  X
} from 'lucide-react';

export const heroIcons = {
  admin: ShieldAlert,
  air: Wind,
  announcement: Megaphone,
  arrowDownRight: ArrowDownRight,
  arrowLeft: ArrowLeft,
  arrowPath: RotateCw,
  arrowUpRight: ArrowUpRight,
  banknotes: Coins,
  bars: Menu,
  bell: Bell,
  bolt: Zap,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  check: CheckCircle,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  city: Building,
  clock: Clock,
  cloud: Cloud,
  dashboard: LayoutDashboard,
  document: FileText,
  energy: Zap,
  eye: Eye,
  eyeSlash: EyeOff,
  flag: Flag,
  government: Landmark,
  health: Activity,
  home: Home,
  map: Map,
  mapPin: MapPin,
  metrics: TrendingUp,
  park: Sun,
  phone: Phone,
  people: Users,
  profile: User,
  report: FileSpreadsheet,
  road: Milestone,
  school: GraduationCap,
  search: Search,
  sparkles: Sparkles,
  star: Star,
  sun: SunIcon,
  trash: Trash2,
  trophy: Trophy,
  truck: Truck,
  users: Users,
  warning: AlertTriangle,
  water: Droplets,
  xCircle: XCircle,
  xMark: X,
};

export default function HeroIcon({ name, className = '', ...props }) {
  const Icon = heroIcons[name] || Sparkles;
  return <Icon className={`hero-icon ${className}`.trim()} strokeWidth={2} aria-hidden="true" {...props} />;
}
